### ISSUE TITLE
cannot find task iis, asp.net

### ISSUE THREAD

**Issue by focusede** [dahall/TaskScheduler#858] opened 2020-11-05 15:57 UTC
Hi, first off thank you for this wrapper.  It seems to do exactly what I need, which is missing in my life.

On a Win2016 server, I have manually created a task which runs an exe.  I am hoping just to trigger that task from my asp.net application.

`      using (var ts = new TaskService())
            {
                // This will find it even if its down in a folder. 
                var t = ts.FindTask(sTaskName);
                if (t != null)
                {
t.Run();
{`

So what is happening is t is always null.  I have searched but am hoping you can point me to the right way to execute this task.  On a local machine (win10) I was able to run my simple task.  Is there a step by step guide somewhere describing what must be done for the task to be found and run?

**Comment by dahall** [comment] 2020-11-05 16:04
Duplicate of #859

**Closed as completed by dahall** 2020-11-05 16:04 UTC
