### ISSUE TITLE
AccessViolation closing TaskSchedulerEditor

### ISSUE THREAD

**Issue by AnnsTech** [dahall/TaskScheduler#795] opened 2019-01-25 08:21 UTC
The open Task.ShowEditor()-dialog throws an AccessViolationException on closing by either Cancel or close.

**To Reproduce**
1. Create an application with the code snippets below
2. Create a simple task in windows taskEditor, named "BackupTask"
2. Run the application
3. Press Button, then the Task-Editor window will open
4. Close the task-editor window by either pressing cancel or ok. Doing so I get at least every 3-4 times an access violation and application crashes.

**Expected behavior**
The task-editor window closes without error.

**Environment (please complete the following information):**
 - Windows 10 pro
 - Library version: TaskSchedulerEditor 2.8.7
 - Visual Studio Enterprise 2017
 
**Code**
Xaml:
Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d"
        Title="MainWindow" Height="300" Width="500">
    Grid>
        Button Content="Button" HorizontalAlignment="Left" Margin="200,100,0,0" VerticalAlignment="Top" Width="75" Click="Button_OnClick" />
    Grid>
Window

MainWindow.xaml.cs:

using System.Windows;
using Microsoft.Win32.TaskScheduler;
namespace WpfApp1
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
        private void Button_OnClick(object sender, RoutedEventArgs e)
        {
            using (var service = new TaskService())
            {
                var task = service.AllTasks.First(x=>x.Name.Equals("BackupTask"));
                task.ShowEditor();
            }
        }
    }
}

**Comment by dahall** [comment] 2019-02-02 19:10
I have your config and running this exact code 12 times, did not encounter a single error. Win10 (1803), Lib 2.8.7.

**Comment by dahall** [comment] 2019-02-08 04:30
Are you still seeing the issue?

**Comment by AnnsTech** [comment] 2019-02-13 12:14
Yes, but I do not use the editor anymore.
I still have the AccessViolation. Win10 (1809), Lib 2.8.7

**Comment by dahall** [comment] 2019-02-13 15:54
There may be a corruption issue with the NuGet package. Another user reported that after deleting and re-downloading the Editor package, a similar exception went away. Would you mind trying that?

**Comment by AnnsTech** [comment] 2019-02-14 08:18
No. Deleted and downloaded nuget package but the access violation still occurs.

**Comment by dahall** [comment] 2019-02-14 14:33
Thanks for trying that. I'll keep looking.

**Comment by dahall** [comment] 2019-04-12 20:03
Was this resolved? Can I close the issue?

**Comment by cityfamer** [comment] 2019-10-18 05:35
> I have your config and running this exact code 12 times, did not encounter a single error. Win10 (1803), Lib 2.8.7.

I get this error in win10

**Comment by dahall** [comment] 2019-10-18 12:35
@cityfamer Will you provide more detail on how you reproduce the error?

**Comment by AnnsTech** [comment] 2019-10-23 07:53
Hi David,

 

I tested the new version about 10-15 times and did not get an AccessViolation anymore.

 

But closing the window with changes returned a Object not set to a reference.

Well, I should investigate it in more detail and give you some more information, but I have no time at the moment.

 

But thanks a lot!

Annegret
 

 


Gesendet: Freitag, 18. Oktober 2019 um 14:35 Uhr
Von: "David Hall" <notifications@github.com>
An: dahall/TaskScheduler <TaskScheduler@noreply.github.com>
Cc: AnnsTech <As.tech@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [dahall/TaskScheduler] AccessViolation closing TaskSchedulerEditor (#795)


@cityfamer Will you provide more detail on how you reproduce the error?

**Comment by NobsterTheLobster** [comment] 2019-10-24 13:06
I am still experiencing AccessViolation Errors. 

Windows 10 1903 x64 (but app is running x86) 
.NET 4.5
Visual Studio 2019
TaskScheduler 2.8.16
TaskSchedulerEditor 2.8.16

As the previous post the errors mostly occur on cancelling from the TaskEditDialog as opposed to clicking OK.
```

               using (var taskwiz = new TaskEditDialog(t, true))
                    {
                        //Show the dialog.
                        taskwiz.ShowDialog();
                    }
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.DisabledItemComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, Int32 wParam, Int32 lParam)
   at System.Windows.Forms.ComboBox.get_SelectedIndex()
   at System.Windows.Forms.ComboBox.OnHandleDestroyed(EventArgs e)
   at System.Windows.Forms.DisabledItemComboBox.OnHandleDestroyed(EventArgs e)
   at System.Windows.Forms.Control.WmDestroy(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.DisabledItemComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by dahall** [comment] 2019-10-24 14:24
Thank you @NobsterTheLobster! Your stack trace has finally helped me identify where the problem could be. I'll spend some time trying to duplicate and then remove the problem this week.

**Comment by dahall** [comment] 2019-10-24 16:12
@cityfamer , @AnnsTech , and @NobsterTheLobster : I have a build that puts a bunch of null and disposed checks into DisabledItemComboBox. I have created a very simple test program in VS2019, .NET 4.5 using this build and never see exceptions. I never saw them before either, so I'm not sure that's valid. I have attached both the NuGet packages (v2.8.17) as well as the two raw assemblies with supporting PDB and XML files in a single ZIP file [TaskScheduler.2.8.17.Test.zip](https://github.com/dahall/TaskScheduler/files/3768535/TaskScheduler.2.8.17.Test.zip). Please test and let me know if the exception is gone.

**Comment by dahall** [comment] 2019-10-25 12:41
Are you running a program that launches the TaskEditDialog on command, for example when you click a button, and remains running while you open and close the TaskEditDialog multiple times until it throws the exception? (I'm trying to determine how to best reproduce what you're seeing.)

**Comment by dahall** [comment] 2019-10-25 13:22
And, are you constructing a new instance of TaskEditDialog each time or reusing a single instance?

**Comment by NobsterTheLobster** [comment] 2019-10-29 06:30
> Are you running a program that launches the TaskEditDialog on command, for example when you click a button, and remains running while you open and close the TaskEditDialog multiple times until it throws the exception? (I'm trying to determine how to best reproduce what you're seeing.)

Yes that's exactly it.

> And, are you constructing a new instance of TaskEditDialog each time or reusing a single instance?

Its a new instance of the taskEditDialog each time but not necessarily a new task, The quickest way to reproduce is having an existing (already registered) task that I keep opening to edit.

**Comment by NobsterTheLobster** [comment] 2019-10-29 07:55
Hi David I think I have figured something out and possibly you can close this issue.

Normally in a winforms project the lines below get automatically added by visual studio. However in my case the lines were missing because my project started out as a console application and evolved into a winforms project.  

I wanted to create you a repro project so I started from the beginning with the most simplest of projects and then gradually introduced the code from the real app. I had almost added all of the real app code before I noticed that the task edit dialog actually looked slightly different in the real app versus the test app and that is when I realised the lines below were missing from the real app. It seems to me that the crashes appear when these lines are missing.

```
                Application.EnableVisualStyles();
                Application.SetCompatibleTextRenderingDefault(false);
```
[TestTaskScheduler.zip](https://github.com/dahall/TaskScheduler/files/3782234/TestTaskScheduler.zip)

Note you will have some problems running the attached project because I have routed my nuget packages folder to C:\Packages. You should be able to do a find in the project file for "C:\Packages" and replace it with "..\Packages" or whatever it should be. Sorry for the inconvenience.

**Comment by LiamMellor71** [comment] 2019-10-29 12:44
Nobster

I too was experiencing exactly the same scenario as you had.
My application launches from a module and determines whether it needs to run without forms or there is user interactivity and needs forms.
I placed the two above lines in the start module and i no longer get the Access Violations either.

Great spot.

Liam

**Comment by dahall** [comment] 2019-11-09 22:29
I cannot reproduce this problem, even without those method calls. In 2.8.17 I have added some disposal checking to `DisabledItemComboBox` in hopes of fixing the problem. Thanks for all your help and suggestions.

**Closed as completed by dahall** 2019-11-09 22:29 UTC
Labels: bug
